name: Rspec

on:
  push:
    branches:
      - '**'

jobs:
  Rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2

      - name: Set timezone
        run: sudo timedatectl set-timezone Europe/Minsk

      - name: Build app
        uses: ./.github/actions/prebuild_app

      - name: Setup DB
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_HOST: localhost
        run: bundle exec rails db:setup

      - name: Test DB
        run: bundle exec rspec
